# Generated by Django 2.0.2 on 2019-07-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190722_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
